name: 'Build UnityPackage.'

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  unitypackage:
    runs-on: ubuntu-latest

    name: 'Build UnityPackage.'

    permissions:
      contents: write

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          lfs: 'true'

      - name: 'setup Unity'
        uses: buildalon/unity-setup@30fcbcb56c10ea5d64298e970d952b8d29bc268b # v2.6.0
        id: unity-setup
        with:
          unity-version: '6000.3.10f1'
          cache-installation: 'true'

      - name: 'Activate Unity license'
        uses: buildalon/activate-unity-license@e0d245d0787b7b9931b56ccbde3b508f6b70f1af # v2.2.2
        with:
          license: 'personal'
          username: '${{ secrets.UNITY_CI_USERNAME }}'
          password: '${{ secrets.UNITY_CI_PASSWORD }}'

      - name: 'Build Package'
        run: ${{ steps.unity-setup.outputs.unity-editor-path }} -quit -batchmode -nographics -projectPath $(pwd) -executeMethod ResoniteSDK_Builder.BuildUnityPackage
  
      - name: 'Upload packages'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # V7.0.1
        with:
          name: 'Resonite.UnitySDK'
          path: Builds/*.unitypackage

      - name: 'Publish package to release if any.'
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: softprops/action-gh-release@b4309332981a82ec1c5618f44dd2e27cc8bfbfda # v3.0.0
        with:
          files: 'Builds/ResoniteSDK.unitypackage'
