name: 'Build UnityPackage.'

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  unitypackage:
    runs-on: ubuntu-latest

    name: 'Build UnityPackage.'

    steps:
      - name: 'Checkout repository'
        uses: actions/checkout@v6
        with:
          lfs: 'true'

      - name: 'setup Unity'
        uses: buildalon/unity-setup@v2
        id: unity-setup
        with:
          unity-version: '6000.3.10f1'
          cache-installation: 'true'

      - name: 'Activate Unity license'
        uses: buildalon/activate-unity-license@v2
        with:
          license: 'personal'
          username: '${{ secrets.UNITY_CI_USERNAME }}'
          password: '${{ secrets.UNITY_CI_PASSWORD }}'

      - name: 'Build Package'
        run: ${{ steps.unity-setup.outputs.unity-editor-path }} -quit -batchmode -nographics -projectPath $(pwd) -executeMethod ResoniteSDK_Builder.BuildUnityPackage
  
      - name: 'Upload packages'
        uses: actions/upload-artifact@v7
        with:
          name: 'Resonite.UnitySDK'
          path: Builds/*.unitypackage

      - name: 'Publish package to release if any.'
        if: ${{ github.event_name == 'release' && github.event.action == 'published' }}
        uses: softprops/action-gh-release@v2
        with:
          files: 'Builds/ResoniteSDK.unitypackage'
